### PR TITLE
More mDNSPosix Fixes

### PR DESCRIPTION
**Pull request by agners**
This builds on #2, but contains an additional fix to address a `SIGSEGV`.

### CODE REVIEW

**Comment by nkarstens** [comment]
@agners Thanks for finding that. To make it easier for the maintainers, would you mind instead if we bring that into #2 and close this PR? Three ways I can think of doing that:

1. I cherry-pick your change
2. You create a PR on my fork
3. I amend 00289e89cccb9567d6ea6bd2a394fd14b61e5ad1 and add "Co-authored-by" and "Signed-off-by" tags for you.

What is your preference?

**Comment by agners** [comment]
@nkarstens thanks for your work!

> What is your preference?

Either way works for me, I think the simplest would be if you just cherry-pick my change (so 1).

I've noticed that the latest version (1807.101.2) doesn't seem to have a working POSIX implementation at all? :confused: 

```
$ cd mDNSPosix
$ make os=linux
make: *** No rule to make target 'objects/prod/PosixDaemon.c.o', needed by 'build/prod/mdnsd'.  Stop.
```

**Comment by akiernan** [comment]
> I've noticed that the latest version (1807.101.2) doesn't seem to have a working POSIX implementation at all? 😕
> 
> ```
> $ cd mDNSPosix
> $ make os=linux
> make: *** No rule to make target 'objects/prod/PosixDaemon.c.o', needed by 'build/prod/mdnsd'.  Stop.
> ```

It pretty much has no source at all...

```
~/mDNSResponder$ find . -name '*.c' | wc -l
0
```

**Comment by nkarstens** [comment]
Thanks, @agners, I cherry-picked your change into #2. You may consider closing this now.

I also noticed that most of the source files have disappeared in their latest push. I suspect that was an oversight but will try to follow up.

**Comment by dhgutteridge** [comment]
> Thanks, @agners, I cherry-picked your change into #2. You may consider closing this now.
> 
> I also noticed that most of the source files have disappeared in their latest push. I suspect that was an oversight but will try to follow up.

Yes, it appears to be a merge botch where much of the project is lost, so there'd be nothing relevant left to apply changes to. There doesn't seem to be any means of communicating this I can see other than via PRs like this one, since I can find no bug reporting contact details, nor is issue reporting enabled for this project. (This is relevant in my case as this is the upstream source for integration into NetBSD, which we're, well, lagging behind on.)

**Comment by agners** [comment]
Close in favor of #2.

**Pull request closed without merging**
